### ISSUE TITLE
Cask error

### ISSUE THREAD

**Issue by johnbwoodruff** [erikdonohoo/mac-setup#1]
[This line](https://github.com/erikdonohoo/mac-setup/blob/master/setup.sh#L92) has an error. You did `brew cash` instead of `brew cask`.

Although I'd love me some brew cash.

**Comment by erikdonohoo** [comment]
Pfft.  You're acting like I _actually_ ran this script.  This is just decorational. 😄   I need to update that.  My first time using this I ran it manually line by line.  I noticed that and ran it correctly, but didn't update the script.
